### ISSUE TITLE
Annotation proxy reports 401 error when using HTTP Authorization request headers

### ISSUE THREAD

**Issue by jvendetti** [sifrproject/annotators#26] opened 2018-10-09 19:32 UTC
We're working on trying to get the AnnotatorPlus up and running within Stanford's [BioPortal application](http://bioportal.bioontology.org/). Alex set up an [instance of the annotation proxy](http://services.stage.bioontology.org/annotatorplus/) and we've noticed that we get 401 errors if we try to access the /annotatorplus endpoint with an HTTP Authorization request header. Screen shot with particulars in Postman:

![screenshot 2018-10-09 12 19 31](https://user-images.githubusercontent.com/1696923/46693031-98f12c80-cbbd-11e8-92e3-ddbc4ef8ee0e.png)

The same call succeeds if the BioPortal API key is provided in the query string instead of the Authorization header:

![screenshot 2018-10-09 12 21 34](https://user-images.githubusercontent.com/1696923/46693146-e1a8e580-cbbd-11e8-81ad-5c046b033a2a.png)

There does appear to be code that [looks for the Authorization header](https://github.com/sifrproject/annotators/blob/master/sifr-bioportal-annotator-proxy/src/main/java/org/sifrproject/servlet/AnnotatorServlet.java#L268). Wondering if there's any information you could provide to assist us in getting this working?

**Comment by twktheainur** [comment] 2018-10-09 19:58
@jvendetti Which commit and branch did Alex clone from? There is code that should handle this case, but I suspect it may do so only for POST requests. 
I am investigating the issue.

**Comment by twktheainur** [comment] 2018-10-09 20:10
It's not restricted to POST requests, if there are authorization headers, they should be transferred to the proxy request. That's the case in the master branch anyway. I see that the ncbo_annotatorplus branch is a few commits behind master, where there is an older version of the request forwarding code running. Merging with master may fix it. Once I know which branch this occurs on, I will attempt to reproduce in debug mode and see where it goes wrong more precisely.

**Comment by jvendetti** [comment] 2018-10-09 20:14
Thanks @twktheainur. I've asked Alex to get you this information.

**Comment by alexskr** [comment] 2018-10-09 20:42
I used ncbo_annotator branch
should we use ncbo_annotatorplus  instead?

**Comment by twktheainur** [comment] 2018-10-09 20:59
ncbo_annotator is an old branch that's been last updated in 2015, before my overhaul, which is probably why this issue arose. ncbo_annotatorplus is the one I created during my visit if I remember correctly. That being said, I have since updated the master branch with maven profiles for each of the deployment targets. 

So if you get HEAD master and build with mvn install -P ncboannotatorplus, it should build the war properly. 

If you need to change the settings, you can modify `sifr-bioportal-annotator-proxy/src/main/resources/ncboannotatorplus/annotatorProxy.properties`

**Comment by alexskr** [comment] 2018-10-09 21:01
that was the issue.  looks like I checked out the wrong branch in my local dev environment.  Things are back in order.

**Closed** 2018-10-09 21:03 UTC
Labels: bug
